# -*- coding: utf-8 -*-
"""PSI_DE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oWmQcpg1mW0WOHsBAEnD4Sx6s0-599r5
"""
#Installing pyspark version 3.4.0 on collab

!pip install pyspark==3.4.0

#Confirming csv file uploads
!ls

#Importing pyspark Libraries
import os
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import (
    StructType, StructField,
    StringType, IntegerType, DoubleType
)

spark = (
    SparkSession.builder
    .master("local[*]")
    .appName("PSI_Ecommerce_Pipeline")
    .config("spark.sql.legacy.timeParserPolicy", "LEGACY")
    .getOrCreate()
)
spark.sparkContext.setLogLevel("WARN")
print("SparkSession created")

ORDERS_SCHEMA = StructType([
    StructField("order_id",     StringType(), True),
    StructField("customer_id",  StringType(), True),
    StructField("order_date",   StringType(), True),
    StructField("status",       StringType(), True),
    StructField("total_amount", DoubleType(), True),
    StructField("discount_pct", DoubleType(), True),
])

ORDER_ITEMS_SCHEMA = StructType([
    StructField("item_id",    StringType(),  True),
    StructField("order_id",   StringType(),  True),
    StructField("product_id", StringType(),  True),
    StructField("quantity",   IntegerType(), True),
    StructField("unit_price", DoubleType(),  True),
    StructField("category",   StringType(),  True),
])

CUSTOMERS_SCHEMA = StructType([
    StructField("customer_id",   StringType(), True),
    StructField("signup_date",   StringType(), True),
    StructField("country",       StringType(), True),
    StructField("customer_tier", StringType(), True),
    StructField("email",         StringType(), True),
])

RETURNS_SCHEMA = StructType([
    StructField("return_id",     StringType(), True),
    StructField("order_id",      StringType(), True),
    StructField("return_date",   StringType(), True),
    StructField("reason",        StringType(), True),
    StructField("refund_amount", DoubleType(), True),
])

print("Schemas defined")

def load_csv(spark, path, schema, table_name):
    """
    Load CSV with explicit schema using PERMISSIVE mode.
    Returns df_clean and df_rejected separately.
    """
    df_raw = (
        spark.read
        .option("header", "true")
        .option("mode", "PERMISSIVE")
        .option("columnNameOfCorruptRecord", "_corrupt_record")
        .schema(schema)
        .csv(path)
    )

    if "_corrupt_record" not in df_raw.columns:
        df_raw = df_raw.withColumn("_corrupt_record", F.lit(None).cast(StringType()))

    df_rejected = (
        df_raw
        .filter(F.col("_corrupt_record").isNotNull())
        .withColumn("source_table", F.lit(table_name))
    )

    df_clean = df_raw.filter(F.col("_corrupt_record").isNull()).drop("_corrupt_record")

    total    = df_raw.count()
    rejected = df_rejected.count()
    clean    = df_clean.count()
    print(f"[{table_name}] total={total:,}  clean={clean:,}  rejected={rejected:,}")

    return df_clean, df_rejected

orders_raw,      orders_rejected      = load_csv(spark, "orders.csv",      ORDERS_SCHEMA,      "orders")
order_items_raw, order_items_rejected = load_csv(spark, "order_items.csv", ORDER_ITEMS_SCHEMA, "order_items")
customers_raw,   customers_rejected   = load_csv(spark, "customers.csv",   CUSTOMERS_SCHEMA,   "customers")
returns_raw,     returns_rejected     = load_csv(spark, "returns.csv",      RETURNS_SCHEMA,     "returns")


# 4. Combine all rejected rows into one log

rejected_all = (
    orders_rejected
    .unionByName(order_items_rejected, allowMissingColumns=True)
    .unionByName(customers_rejected,   allowMissingColumns=True)
    .unionByName(returns_rejected,     allowMissingColumns=True)
)

rejected_count = rejected_all.count()
print(f"\n[REJECTED TOTAL] {rejected_count:,} rows")

print(" Task 01 complete — all tables ingested with explicit schemas.")

"""# TASK 2
 Data cleaning and Quality checks
  
"""

# Step 1 — Removing exact duplicate rows
orders_dedup      = orders_raw.dropDuplicates()
order_items_dedup = order_items_raw.dropDuplicates()
customers_dedup   = customers_raw.dropDuplicates()
returns_dedup     = returns_raw.dropDuplicates()

print("After deduplication:")
print(f"  orders:      {orders_raw.count():,} → {orders_dedup.count():,}")
print(f"  order_items: {order_items_raw.count():,} → {order_items_dedup.count():,}")
print(f"  customers:   {customers_raw.count():,} → {customers_dedup.count():,}")
print(f"  returns:     {returns_raw.count():,} → {returns_dedup.count():,}")

"""Normalizing the date

"""

def normalize_date(col_name):
    """
    Handles two incoming formats:
      - YYYY-MM-DD  (ISO)
      - DD/MM/YYYY
    Returns a DateType column in ISO format.
    """
    return F.coalesce(
        F.to_date(F.col(col_name), "yyyy-MM-dd"),
        F.to_date(F.col(col_name), "dd/MM/yyyy")
    )

# Step 2 — Normalize date columns to ISO format (YYYY-MM-DD)

orders_dated = orders_dedup.withColumn("order_date", normalize_date("order_date"))

customers_dated = customers_dedup.withColumn("signup_date", normalize_date("signup_date"))

returns_dated = returns_dedup.withColumn("return_date", normalize_date("return_date"))

print(" Date columns normalised to YYYY-MM-DD")

# Step 3 — Standardise customer_tier to lowercase

customers_clean = customers_dated.withColumn(
    "customer_tier",
    F.lower(F.col("customer_tier"))
)

print("customer_tier standardised to lowercase")

# Step 4 — Drop rows where order_id or customer_id is NULL

orders_before_null_drop = orders_dated.count()

orders_clean = (
    orders_dated
    .filter(F.col("order_id").isNotNull())
    .filter(F.col("customer_id").isNotNull())
)

dropped_nulls = orders_before_null_drop - orders_clean.count()
print(f"\n Dropped {dropped_nulls:,} orders with NULL order_id or customer_id")

# Step 5 — Flag orders with negative total_amount (do NOT drop)

orders_clean = orders_clean.withColumn(
    "is_negative_amount",
    F.when(F.col("total_amount") < 0, True).otherwise(False)
)

negative_count = orders_clean.filter(F.col("is_negative_amount") == True).count()
print(f"Flagged {negative_count:,} orders with negative total_amount")

print(" Task 02 complete — data quality checks applied.")

# Quick preview
orders_clean.select("order_id", "customer_id", "order_date",
                    "total_amount", "is_negative_amount").show(5)


"""# TASK 3 
Step 1
"""

# Using cleaned order table aas reference
orphaned_items = order_items_dedup.join(
    orders_clean.select("order_id"),
    on="order_id",
    how="left_anti"
)

print(f"Orphaned order_items (no matching order): {orphaned_items.count():,}")

# Writing the orphaned items to a separate output file
orphaned_items.write.mode("overwrite").csv("orphaned_items", header=True)
print("Orphaned items written to ./orphaned_items/")

#Left Join orderr to customers keeping clean order even if customer record is
#missing
orders_with_customers = orders_clean.join(
    customers_clean,
    on="customer_id",
    how="left"  # left join: orders are the primary table
)
print(f"\nAfter orders ← customers join: {orders_with_customers.count():,} rows")

# Inner join with order_items
# Inner join: only keep orders that have at least one line item
# Exclude orphaned items from this join

valid_items = order_items_dedup.join(
    orders_clean.select("order_id"),
    on="order_id",
    how="inner"
)

enriched = orders_with_customers.join(
    valid_items,
    on="order_id",
    how="inner"
)

print(f"After orders ← order_items join: {enriched.count():,} rows")


# Step 4 — Derive net_amount
# net_amount = total_amount * (1 - discount_pct / 100)

enriched = enriched.withColumn(
    "net_amount",
    F.round(
        F.col("total_amount") * (1 - F.col("discount_pct") / 100),
        2
    )
)

print("net_amount derived")
print("Task 03 complete — joins and enrichment done.")

# Previewing

enriched.select(
    "order_id", "customer_id", "country", "customer_tier",
    "category", "total_amount", "discount_pct", "net_amount"
).show(5)

"""# TASK 4"""

from pyspark.sql.window import Window


# 1. Define Window for Customer Spending
customer_window = Window.partitionBy("customer_id").orderBy("order_date")

# 2. Add Running Total and Previous Transaction Amount
enriched_df = enriched.withColumn("running_total", F.sum("net_amount").over(customer_window)) \
                .withColumn("prev_amount", F.lag("net_amount", 1).over(customer_window)) \
                .withColumn("spending_change", F.col("net_amount") - F.col("prev_amount"))

# 3. Show Results without using .toPandas()
enriched_df.show(10)